FROM php:7.2-apache
MAINTAINER Mike Pretzlaw <mail@mike-pretzlaw.de>

WORKDIR /var/www

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# update
RUN apt-get update \
    && apt-get upgrade -qy

# basics
RUN apt-get install -qqy curl unzip vim wget

# @docker-recipe vcs

# @docker-recipe php/composer

# cleanup
RUN rm -rf /var/lib/apt/lists/*
